---
- name: Add EPEL repo
  yum_repository:
    name: epel
    description: Epel repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Import EPEL GPG key
  rpm_key:
    key: "https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
    state: present

- name: Update all packages
  yum:
    name: '*'
    state: latest

- name: Install basic packages
  yum: name={{ item }} state=installed
  with_items:
    - mc
    - vim
    - htop
    - atop
    - wget
    - zip
    - unzip
    - ntp
    - libselinux-python
    - libsemanage-python
    - bash-completion
    - git

- name: Disable Selinux
  selinux:
    state: disabled

- name: Stop firewalld
  systemd: name=firewalld state=stopped

- name: Disable firewalld
  systemd: name=firewalld enabled=no

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


- name: Change prompt
  lineinfile: dest=/etc/bashrc regexp="^PS1=" line="PS1='\T \[\e[1;37m\][ \[\e[1;32m\]\u \[\e[1;37m\]\H\[\e[1;30m\]\[\e[0;32m\]\[\e[1;37m\] ] \[\e[1;32m\]\w\[\e[0;37m\] '"

- name: Set timezone
  timezone:
    name: Europe/Kiev

- name: Enable NTP
  systemd: name=ntpd enabled=yes state=started

- name: Reboot machine
  shell: sleep 2 && /sbin/shutdown -r now "Ansible system package upgraded"
  async: 1
  poll: 0

- name: Waiting for reboot complete
  local_action: wait_for host={{ ansible_host }} state=started delay=30 timeout=60
